version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: fc308ed37e749d66e41ddde4d2a27765b6ffeef87e3e8e254c0111ed5180d66b

    docker:
      - image: gobble/python:3.6

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: Configure Docker Image Env Variable
          command: |
            echo 'export DOCKER_IMAGE=gobble/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1' >> $BASH_ENV
            echo 'export SHELL_SCRIPT_TO_RUN_APP=run_app.sh' >> $BASH_ENV
            # echo 'export CC_TEST_REPORTER_ID=fc308ed37e749d66e41ddde4d2a27765b6ffeef87e3e8e254c0111ed5180d66b' >> $BASH_ENV

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Building Docker Image
          command: |
            docker build -t  $DOCKER_IMAGE .

      - run:
          name: Running Tests
          command: |
            ./cc-test-reporter before-build
            docker run \
              --env AWS_ACCESS_KEY_ID \
              --env AWS_SECRET_ACCESS_KEY \
            -it $DOCKER_IMAGE /bin/bash -c \
              'source $VENV_DIR/bin/activate; \
              pytest --cov=src tests/test_*.py'
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
